name: Slow CI 😢
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Initialise
      run: sudo apt-get update && sudo apt-get upgrade -y
    - name: Build Docker Image
      run: docker build ./level1 --file level1/Dockerfile --tag ci-racer/level1:0.0.1
    - name: Run Tests
      run: docker run -e CI=true ci-racer/level1:0.0.1 npm run test
