name: Slow CI :(
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Code
    - name: Build Docker Image
    - run: docker build level1 --file Dockerfile --tag ci-racer/level1:0.0.1
