name: Slow CI :(
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build ./level1 --file level1/Dockerfile --tag ci-racer/level1:0.0.1
